// The design tokens as one plain object: the eight themes (ui / syntax / to-do
// roles), the to-do grammar's order and aliases, and the to-do glyphs. This is
// the contract the iPhone companion paints note content from, written to
// shared/design-tokens.json by scripts/export-design-tokens.mjs and checked
// for staleness by design-tokens.test.ts. Nothing here is declared twice: it
// reads the same tables the Mac renders from.

import { ALIASES, ORDER } from "./todo-model";
import { kindOf, todoGlyphSvg } from "./todo-glyph";
import { DEFAULT_THEME_ID, THEMES } from "./themes";

export function designTokens() {
  return {
    _comment:
      "Generated by scripts/export-design-tokens.mjs from src/lib — do not edit by hand. The iPhone companion paints note content from this file so both apps stay one design.",
    themes: THEMES.map((t) => ({
      id: t.id,
      label: t.label,
      mode: t.mode,
      ui: t.ui,
      syntax: t.syntax,
      todo: t.todo,
    })),
    defaultThemeId: DEFAULT_THEME_ID,
    todo: {
      order: [...ORDER],
      aliases: ALIASES,
      // The checkbox, as App.css draws it: a 0.95em square at the line's font
      // size; inside, a 1.5px border with 4px radius at 0.7em, the svg 0.85em.
      box: {
        size: "0.95em",
        border: "1.5px",
        radius: "4px",
        glyphFontSize: "0.7em",
        svgSize: "0.85em",
      },
      // Lucide glyphs, verbatim, already scaled to one ink size and stroke —
      // the exact string the Mac's editor and preview both render.
      glyphs: Object.fromEntries(ORDER.map((st) => [st, todoGlyphSvg(kindOf(st))])),
    },
  };
}

/** The file's exact text, so a byte-for-byte comparison catches staleness. */
export const serializeTokens = (tokens: ReturnType<typeof designTokens>): string =>
  JSON.stringify(tokens, null, 2) + "\n";
