// The design tokens as one plain object: the themes (ui / syntax / to-do
// roles), the to-do grammar's order and aliases, and the to-do glyphs. This is
// the contract the iPhone companion paints note content from, written to
// shared/design-tokens.json by scripts/export-design-tokens.mjs and checked
// for staleness by design-tokens.test.ts. Nothing here is declared twice: it
// reads the same tables the Mac renders from.

import { ALIASES, ORDER } from "./todo-model";
import { kindOf, todoGlyphSvg } from "./todo-glyph";
import { DEFAULT_THEME_ID, THEMES } from "./themes";
import { CODE_WASH, HIGHLIGHT_WASH } from "./palette";
import appCss from "../App.css?raw";

/** A percentage custom property of App.css's :root, as a fraction. */
function cssDial(name: string): number {
  const m = new RegExp(`${name}:\\s*([\\d.]+)%`).exec(appCss);
  if (!m) throw new Error(`App.css has no ${name}`);
  return Number(m[1]) / 100;
}

export function designTokens() {
  return {
    _comment:
      "Generated by scripts/export-design-tokens.mjs from src/lib — do not edit by hand. The iPhone companion paints note content from this file so both apps stay one design.",
    themes: THEMES.map((t) => ({
      id: t.id,
      label: t.label,
      mode: t.mode,
      ui: t.ui,
      syntax: t.syntax,
      todo: t.todo,
      priority: t.priority,
    })),
    defaultThemeId: DEFAULT_THEME_ID,
    // The ground a mark lays under itself: its own colour at this alpha
    // (App.tsx --md-code-bg, --md-highlight-bg).
    washes: { code: CODE_WASH, highlight: HIGHLIGHT_WASH },
    todo: {
      order: [...ORDER],
      aliases: ALIASES,
      // The checkbox, as App.css draws it (--todo-box-*): a 0.8em square at
      // the line's font size, laid out one text column wide and centred on
      // it; a 1.5px border, the radius 0.3 of the side, the glyph 0.5em.
      box: {
        size: "0.8em",
        border: "1.5px",
        radius: "0.24em",
        glyph: "0.5em",
      },
      // A nested line under a to-do: its to-do's colour mixed this far with
      // the page (App.css --todo-child-mix), and the marks on it — bold,
      // italic, code, links, strike, highlight — their own colours mixed by
      // a dial of their own (--todo-child-mark-mix).
      nested: {
        line: cssDial("--todo-child-mix"),
        marks: cssDial("--todo-child-mark-mix"),
      },
      // Lucide glyphs, verbatim, already scaled to one ink size and stroke —
      // the exact string the Mac's editor and preview both render.
      glyphs: Object.fromEntries(ORDER.map((st) => [st, todoGlyphSvg(kindOf(st))])),
    },
  };
}

/** The file's exact text, so a byte-for-byte comparison catches staleness. */
export const serializeTokens = (tokens: ReturnType<typeof designTokens>): string =>
  JSON.stringify(tokens, null, 2) + "\n";
