// The iPhone's first-run sentences, written here as the reference its Swift
// port (ParkerCore FirstRunText) is tested against: they pick keys from the
// same shared/first-run-copy.json, and scripts/export-first-run-lines.mjs
// writes what they say for every situation to shared/fixtures/
// first-run-lines.json, which both suites read. (The counts — contents and
// state — are the Mac's own functions: they say the same on both.)
import { copy, count } from "./first-run";
import type { Tone } from "./first-run";

/** What the iPhone knows about a folder (ParkerCore FolderSummary). */
export interface PhoneFolder {
  exists: boolean;
  notes: number;
  other: number;
  git: boolean;
  gitRemote: string | null;
  /** icloud | dropbox | googleDrive | oneDrive | box | cloudService | onThisPhone | unknown */
  sync: string;
}

const LABELS: Record<string, string> = { dropbox: "Dropbox", googleDrive: "Google Drive", oneDrive: "OneDrive", box: "Box" };
const t = (key: string, vars: Record<string, string | number> = {}) => copy(key, vars, "iphone");

export function phoneContents(f: PhoneFolder): string {
  if (!f.exists) return t("line.contents.new");
  if (!f.notes && !f.other) return t("line.contents.empty");
  if (!f.other) return t("line.contents.notes", { notes: count(f.notes, "note") });
  return t("line.contents.notesOther", { notes: count(f.notes, "note"), other: count(f.other, "otherFile") });
}

export function phoneState(f: PhoneFolder): string {
  if (!f.exists) return t("line.state.new");
  if (!f.notes && !f.other) return t("line.state.empty");
  if (!f.notes) return t("line.state.onlyOther", { other: count(f.other, "file") });
  if (!f.other) return t("line.state.notes", { notes: count(f.notes, "note") });
  return t("line.state.notesOther", { notes: count(f.notes, "note"), other: count(f.other, "otherFile") });
}

export function phoneSync(f: PhoneFolder, driveOn: boolean): { tone: Tone; text: string } {
  if (f.sync === "icloud") return driveOn ? { tone: "ok", text: t("line.sync.icloud") } : { tone: "warn", text: t("line.sync.icloudDriveOff") };
  if (f.sync === "onThisPhone") return { tone: "warn", text: t(driveOn ? "line.sync.here" : "line.sync.hereDriveOff") };
  if (f.sync === "unknown") return { tone: "unknown", text: t("line.sync.unknown") };
  // Another app's cloud that iOS won't name (ParkerCore SyncKind.cloudService).
  if (f.sync === "cloudService") return { tone: "ok", text: t("line.sync.anyService") };
  return { tone: "ok", text: t("line.sync.service", { service: LABELS[f.sync] }) };
}

export function phoneGit(f: PhoneFolder): { tone: Tone; text: string; note: string } {
  if (f.git) return { tone: "ok", text: f.gitRemote ? t("line.git.remote", { remote: f.gitRemote }) : t("line.git.noRemote"), note: t("line.git.note") };
  return { tone: "none", text: t(f.exists ? "line.git.none" : "line.git.new"), note: t("line.git.noneNote") };
}

/** What to do on the Mac to open this same folder. */
export function phoneMacLine(f: PhoneFolder, suggested: boolean, display: string): string {
  if (suggested) return t("line.other.suggested");
  if (f.sync === "icloud") return t("line.other.icloud", { folder: display });
  if (f.sync in LABELS) return t("line.other.service", { service: LABELS[f.sync], folder: display });
  if (f.sync === "cloudService") return t("line.other.anyService", { folder: display });
  if (f.sync === "onThisPhone") return t("line.other.here");
  return t("line.other.unknown");
}

/** shared/fixtures/first-run-lines.json: the iPhone's sentences for every
 *  situation the screens can meet. */
export function phoneFixture() {
  const folders: PhoneFolder[] = [];
  for (const [exists, notes, other] of [[false, 0, 0], [true, 0, 0], [true, 0, 3], [true, 1, 0], [true, 42, 0], [true, 56, 1], [true, 56, 4]] as const)
    for (const git of exists ? [false, true] : [false])
      for (const gitRemote of git ? [null, "you/notes"] : [null])
        for (const sync of ["icloud", "googleDrive", "dropbox", "cloudService", "onThisPhone", "unknown"])
          folders.push({ exists, notes, other, git, gitRemote, sync });
  const cases = [];
  for (const f of folders)
    for (const driveOn of [true, false])
      for (const suggested of f.sync === "icloud" ? [true, false] : [false]) {
        const display = f.sync === "icloud" ? "iCloud Drive › Documents › Parker" : "Google Drive › My Drive › Notes";
        cases.push({
          folder: f,
          driveOn,
          suggested,
          display,
          contents: phoneContents(f),
          state: phoneState(f),
          sync: phoneSync(f, driveOn),
          git: phoneGit(f),
          mac: phoneMacLine(f, suggested, display),
        });
      }
  return {
    $comment:
      "Generated by scripts/export-first-run-lines.mjs from src/lib/first-run-iphone.ts and shared/first-run-copy.json — do not edit by hand. The iPhone's first-run sentences for every situation; ParkerCore FirstRunTests read it.",
    cases,
  };
}
