// The note painter as the iPhone calls it (shared/parker-paint.js, a global
// `ParkerPaint` in JavaScriptCore): a note's text in, its paint as JSON out —
// one string across the bridge, decoded on the Swift side (NotePainter.swift).
import { paintNote } from "./paint";
import { PAINT_CASES } from "./paint-cases";

export function paint(text: string): string {
  return JSON.stringify(paintNote(text));
}

/** shared/fixtures/note-paint.json: the cases and what they paint. */
export function fixture() {
  return {
    $comment:
      "Generated by scripts/export-note-paint.mjs from src/lib/paint.ts — do not edit by hand. Each line's tone, the to-do tag drawn as a box, and runs of [from, to) UTF-16 offsets with a colour role. Checked against the Mac's real editor by src/lib/paint.view.test.ts; the iPhone's NotePainterTests read it too.",
    cases: PAINT_CASES.map((c) => ({ ...c, lines: paintNote(c.note) })),
  };
}

export const serializeFixture = (f: ReturnType<typeof fixture>): string => JSON.stringify(f, null, 1) + "\n";
