// The notes shared/fixtures/note-paint.json is made of: every way the editor
// colours a note, and the places where two rules meet. The Mac's real editor
// is checked against the painter over these (paint.view.test.ts), and the
// iPhone against the fixture (ParkerCore NotePainterTests).
export const PAINT_CASES: { name: string; note: string }[] = [
  {
    name: "headings",
    note: ["# One", "## Two with **bold** and `code`", "###### Six", "Setext", "---", "#not a heading"].join("\n"),
  },
  {
    name: "marks",
    note: [
      "Plain *it* _it_ **bo** __bo__ ***bi*** `code` ~~gone~~ ==pen==",
      "Nested **bold *and it* bold** and *it **and bold** it*",
      "**~~bold strike~~** and ==**pen bold**== and `**not bold**`",
      "Escaped \\*not it\\* and a lone * star",
    ].join("\n"),
  },
  {
    name: "links and urls",
    note: [
      "A [link](https://a.dev) and a bare https://b.dev, and www.c.dev.",
      "An <https://d.dev> autolink and [a titled one](https://e.dev \"Title\")",
      "(https://f.dev/path_(x)) in brackets, and not.a.url",
      "![an image](img/photo.png) and [relative](notes/other.md)",
      "Mail me at user@host.dev or [mail](mailto:user@host.dev)",
    ].join("\n"),
  },
  {
    name: "quotes and lists",
    note: [
      "> a quote with **bold**, `code` and [l](https://g.dev)",
      "> > nested quote",
      "- item with *it* and https://h.dev",
      "  - sub item",
      "  continuation of the item",
      "1. first",
      "2) second",
      "* star item",
      "- > quote in a list",
      "",
      "Paragraph after.",
    ].join("\n"),
  },
  {
    name: "code",
    note: [
      "```",
      "fenced **not bold** https://i.dev",
      "```",
      "",
      "```js",
      "const x = 1; // named: the Mac highlights it as JavaScript once loaded",
      "```",
      "",
      "    indented code after a blank line",
      "",
      "~~~",
      "tilde fence",
      "~~~",
    ].join("\n"),
  },
  {
    name: "to-do states",
    note: [
      "/TODO open with **bold** and https://j.dev",
      "/DOING in progress with *it*, `code`, [l](https://k.dev) and https://l.dev",
      "/PAUSE paused",
      "/WAIT waiting ~~x~~ ==y==",
      "/ATTN attention",
      "/DONE done ***bi***",
      "/FAIL failed",
      "/CANCEL dropped",
      "/WIP alias of doing",
      "/DISMISSED alias of cancel",
      "/TODO!!! high priority",
      "/DOING! low priority",
      "/TODOS not a tag",
      "text /TODO mid-line",
      "/TODO",
    ].join("\n"),
  },
  {
    name: "under a to-do",
    note: [
      "/DOING parent",
      "  a detail with **bold** *it* `code` [l](https://m.dev) https://n.dev ~~s~~ ==h==",
      "  - a sub item",
      "  /TODO a nested to-do with **bold**",
      "    under the nested to-do *it*",
      "",
      "    after a blank line, still under it",
      "  /DONE nested done",
      "    under nested done",
      "back at the margin *it*",
      "/CANCEL dropped",
      "  under cancel **b**",
      "/TODO open parent",
      "  under open **b**",
      "- list item",
      "  /DOING to-do in a list",
      "    under it",
    ].join("\n"),
  },
  {
    name: "a note's shape",
    note: [
      "# Weather widget",
      "",
      "A menu-bar widget that shows the next two hours of weather, and nothing else.",
      "",
      "/DONE Pick a weather API: free, no key",
      "  - C: Open-Meteo (`api.open-meteo.com`): free, no key.",
      "/ATTN!! Celsius or Fahrenheit?",
      "  - **(a) Celsius**: most of the world.",
      "/TODO Draw the menu-bar icon",
      "",
      "## Notes",
      "",
      "Name it: Drizzle?",
    ].join("\n"),
  },
];
